### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by ashleyjross**
@weaverba137 does this look good?

### CODE REVIEW

**Comment by weaverba137** [comment]
The text is fine, but are you quite certain you don't want to copy the format of all the other desihub LICENSE.rst files?

**Comment by ashleyjross** [comment]
> The text is fine, but are you quite certain you don't want to copy the format of all the other desihub LICENSE.rst files?

My uncertainty approaches infinity. Just now I copied the one from desi target. Does that work?

**Comment by weaverba137** [comment]
By format, I mean make it a RST file: LICENSE.rst.  I'm sorry that wasn't obvious.  Also, none of the other LICENSE.rst files have `BSD 3-Clause License` as the first line.  To help me root out some potential inconsistencies, which other desihub packages did you look at to create your license file?

**Comment by ashleyjross** [comment]
Here is what I did:
I followed the instructions here for the initial commit and chose the recommended BSD 3-Clause

Then, after your message today, I copied the text here: https://github.com/desihub/desitarget/blob/master/LICENSE.rst

I never noticed the .rst issue. I just edited the file and saved it with .rst. If I go to edit both the one in LSS and desitarget (https://github.com/desihub/desitarget/blob/master/LICENSE.rst), they now match except for the year and the LSS one has "BSD 3-Clause License" at the top. I don't know if there is something else to do or not and I do not find the answer via check on what google tells me.

**Comment by weaverba137** [comment]
Thank you for the information.  Let's go with what you've got now and merge.

**Pull request merged**
