### PR TITLE
Add pixel-level quantities to target files

### PR DESCRIPTION
**Pull request by geordie666**
This PR adds code to process the coadd/stacks files to add pixel-level quantities to the _target_ files, so that they share the exact-same quantities as recorded in the random catalogs.

This started as a request from @rongpu to add pixel-level `NOBS` values for target positions, as the `NOBS` values in the target files differ at the few-percent-level from the pixel-level `nexp` values recorded in the random catalogs.

The resulting files (which are row-by-row parallel with the target files) are available at NERSC in:

`/global/cscratch1/sd/adamyers/nexp`

These reflect the original target files at NERSC in:

`/global/cfs/cdirs/desi/target/catalogs/dr9/1.1.1/targets/main/resolve/dark`

Based on a very recent (i.e. today) exchange with @ashleyjross, @echaussidon and @rongpu, though, we'll want to expand this to add other pixel-level quantities in addition to `NOBS`.

Let's discuss more and converge on exactly which quantities from the random catalogs we should add. Adding them all is possible (and easiest to implement) but it will also be slowest and grow the data model.

@ashleyjross: Thoughts? Should I just modify this work to create row-by-row target files that include "every" plausible quantity from the random catalogs?

### CODE REVIEW

**Comment by ashleyjross** [comment]
I think we definitely want to have at least the columns that are already in the random files. Are there any columns not already in the random files that we could possibly want?

Can we also include the DESI_TARGET column? If yes, that will make it very easy to process these in a parallel fashion to the current LSS process.

**Comment by ashleyjross** [comment]
Excellent; I'll have a look when it is ready.

**Comment by echaussidon** [comment]
Hi Adam, 

Just to mention: I create a MPI code to apply `Maskbits` (adapted from what Rongpu did) to random catalogs (for clustering pipeline purpose) in order to be able to run it quickly and on several nodes. The parallellization is done on the number of bricks to be read in each process (we are dominated by the I/O of the bricks). 

Maybe this can help to decrease the computation time (typically for several Millions of objects it takes few minutes with 16 haswell nodes (ie) 60 bricks per process)

here the link for the code: https://github.com/echaussidon/mockfactory/blob/main/mockfactory/desi/imaging_maskbits.py

**Comment by echaussidon** [comment]
For the columns that we want: It would like the columns for the pixweight file directly in the random and in target files. For the moment, it lacks : PSFDEPTH_W1/W2 for instance ect ...

**Comment by geordie666** [comment]
@ashleyjross: Here's my next iteration. The resulting files are in `/global/cscratch1/sd/adamyers/pixel-dark` and include all of the columns from the pixweight files that aren't in the target files. I've preceded all of the column names with `PIXEL_` to make the origin of the columns clear, but that's easy to change.

These files run in a little over half-an-hour on 24 nodes, which is likely good enough for all ~70 million dark-time targets.

To pick up on something @echaussidon stated: I don't think we want to include this information directly in the target files. I think we want to freeze the target (and random) files as-they-were-produced-by-`desitarget` to ensure exact reproducibility. The files I'm making are row-by-row parallel to the target files, so it will be straightforward to generate new "expanded" target files in the `LSS` context, or to just read in the row-by-row parallel files separately and combine them with the "frozen" target files.

**Comment by ashleyjross** [comment]
This looks great to me! To be clear, the "PIXEL_" in the column name is because the brick pixel was queried and it was done in the same way as for the randoms (which don't have "PIXEL_" in the column name)? I guess the distinction is that for the randoms, we query just the single pixel corresponding to the ra,dec, while the original nobs (and I guess other columns) for the data somehow considered all of the pixels contributing to the source? 

I'm a little confused by what you mean by "These files run in a little over half-an-hour on 24 nodes, which is likely good enough for all ~70 million dark-time targets." Looking at what was produced and pointed to on scratch, it seems you did run it already for everything. (So, given it was done it seems obviously good enough rather than likely and I wonder if I'm missing something.)

These files will be easy to concatenate for each tracer type (given DESI_TARGET) and then match to the LSS catalogs for any version/stage via a targetid match. I agree 100% there is no need to touch the original target files.

**Comment by geordie666** [comment]
Right: I included the `"PIXEL_"` because there are some existing quantities in the target files that have similar names but mean something different. The most obvious, as you noted, are the `NOBS_` columns, which are propagated to the target files from the sweeps but which have a different meaning from the pixel-derived `NOBS_` in the random files. I'd need to check email threads (or reach out to Dustin) to remember/determine exactly how/why the `NOBS_` quantities are different in the original Tractor files — but, regardless, we need to distinguish the randoms-style and Tractor-style derivations of quantities.

I don't think you're missing anything as regards the timings. Those are just notes in case we ever need to update the files. As in "don't worry, this isn't daunting, it only takes minimal resources, we can easily do this again".

Do you think we're ready to merge this PR? If so, my next steps are to make the "bright" versions of the files, and then put all of the `pixel-` files somewhere useful at NERSC. Any recommendations on the best location, given that these are an `LSS` product?

**Comment by ashleyjross** [comment]
I just made a folder named /global/cfs/cdirs/desi/survey/catalogs/extra_target_data . Can you put output there and include the version of targets (e.g., 1.1.1) the files are matched to in the directory structure?

**Comment by geordie666** [comment]
Sounds good, I'll do that later today.

**Comment by geordie666** [comment]
Done — I've put the files in: 

`/global/cfs/cdirs/desi/survey/catalogs/extra_target_data/1.1.1/dark`
`/global/cfs/cdirs/desi/survey/catalogs/extra_target_data/1.1.1/bright`

**Pull request merged**
