### PR TITLE
Scripting alt mt ls

### PR DESCRIPTION
**Pull request by jalasker**
This combination of scripts and altmtltools works for me with desitarget master. 

going to LSS/bin and running "bash MasterAltMTLScript.sh" will produce 64 realizations of SV3-dark in your scratch directory on NERSC, propagate those realizations through all 40 OBSDATEs of SV3 and create bitweights.

If you don't want to run through all of SV3 (e.g. only do one OBSDATE of SV3), you can change parameters in the script file (e.g. change NObsDates to 1). 

@aureliocarnero @michaelJwilson please test that this default setting works for you (probably using the single NObsDate to save core-hours), and then let me know:

1. Does it work
2. Are the necessary options available to run it on your mocks?

N.B. make sure you are on the latest version of desitarget (PR merged over the holiday weekend).

### CODE REVIEW

**Comment by ashleyjross** [comment]
@aureliocarnero @michaelJwilson let me know if pulling this into master would make any tests easier at all (I'm nearly certain the pull would not hurt anything), but otherwise I'll wait for your tests.

**Comment by jalasker** [comment]
@aureliocarnero InitializeAltMTLsParallel will now generate exactly as many realizations as you ask it to rather than defaulting to 64*NNodes

**Comment by ashleyjross** [comment]
@jalasker should we merge this?

**Comment by jalasker** [comment]
I don't know why the bitweights.py file was changed in a way that requires manual merging (appears to just be an import statement no longer being contained in a "try/except" block), but if that's resolved by someone who knows why that change was made, I see no reason why not since it's run fine for me. 

@aureliocarnero we may want to incorporate what you did to patch the script for the mocks in a separate pull request, but since this branch works on the data, we should be okay to merge now.

**Pull request merged**
